### ISSUE TITLE
请设置开源协议

### ISSUE THREAD

**Issue by taozuhong** [codebdy/rxdrag#101]
V2EX 没钱回复了：
你的 RxEditor ，没有选好协议，默认进入公共领域（ Public domain)，大家都可以基于它开发自己的产品并闭源，你的收费蓝图如何实现？   工具类项目开源，一定要选 GPL 类的协议，促使用户回馈代码。

**Comment by codebdy** [comment]
> V2EX 没钱回复了： 你的 RxEditor ，没有选好协议，默认进入公共领域（ Public domain)，大家都可以基于它开发自己的产品并闭源，你的收费蓝图如何实现？ 工具类项目开源，一定要选 GPL 类的协议，促使用户回馈代码。

MIT的package文件里有，谁fork了是谁的

**Comment by codebdy** [comment]
刚看了一下，mit里没了，我加一下

**Comment by codebdy** [comment]
非常感谢，加上了
