### ISSUE TITLE
我进行打包后，产物运行起来是白屏

### ISSUE THREAD

**Issue by zetawoo** [codebdy/rxdrag#260]
在yarn dev调试模式时，web运行正常。但是发布后部署了后是展示的白屏。是不是哪里有什么配置没配配置呢？
使用命令：yarn build
发布内容如下：
![image](https://github.com/codebdy/rxdrag/assets/18661700/9b4b7997-4641-4557-a16e-29fa6971870a)
显示白屏：
![image](https://github.com/codebdy/rxdrag/assets/18661700/932d40f7-b2d1-47b6-b161-65ebaaafc93e)

**Comment by codebdy** [comment]
用pnpm编译运行
