### ISSUE TITLE
bug：点击UI框架中的元素无法显示属性面板，且国际化失效

### ISSUE THREAD

**Issue by superichen** [codebdy/rxdrag#287]
![image](https://github.com/codebdy/rxdrag/assets/121595091/08a136f0-02d4-4f6a-943a-ae683ba0306e)

**Comment by codebdy** [comment]
属性面板不显示，是vercel部署出现的bug，一直没找到原因，本地部署没这个问题

**Comment by superichen** [comment]
@codebdy 但是我的本地也是这样。。

**Comment by codebdy** [comment]
> @codebdy 但是我的本地也是这样。。

加我qq，远程帮你看一下
